# Generated by Django 3.2.25 on 2025-02-01 05:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', ckeditor.fields.RichTextField()),
                ('question_es', models.TextField(blank=True, null=True)),
                ('answer_es', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('question_fr', models.TextField(blank=True, null=True)),
                ('answer_fr', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
