# Generated by Django 3.2.25 on 2025-02-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_es',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_fr',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_es',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_fr',
        ),
    ]
