# Generated by Django 3.2.25 on 2025-02-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250201_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='id',
        ),
        migrations.AddField(
            model_name='faq',
            name='qid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
